name: coins
publish_to: none
description: A package that locally manages the coins/credits of an app in hive database
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.1

dependencies:
  core:
    path: ../core
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

