name: ai_interactions
description: A new Flutter package project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1
homepage:

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  http: ^0.13.0

dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
