name: core
description: A new Flutter package project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1
homepage: null

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  cloud_firestore: ^4.4.4
  firebase_analytics: ^10.1.5
  firebase_core: ^2.7.1
  firebase_crashlytics: ^3.0.16
  firebase_messaging: ^14.6.1
  firebase_remote_config: ^3.0.13
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.4
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  result_type: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  melos: ^3.0.0

flutter: null
